kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "wallaby.fullname" . }}
  labels:
    app: {{ template "wallaby.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "wallaby.fullname" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "wallaby.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
      annotations:
{{- if .Values.config.prometheus.enabled }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9350'
{{- end }}
    spec:
{{- if .Values.rbac.create }}
      serviceAccountName: {{ template "wallaby.fullname" . }}
{{- end }}
      containers:
      - name: wallaby
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - /bin/default-backend-operator
          - -v{{ .Values.config.loglevel }}
          - --statics
          - /static
          - --template
          - /config/index.tpl
          - --entries
          - /config/entries.yaml
{{- if .Values.config.prometheus.enabled }}
          - --prometheus
{{- else }}
          - --prometheus
          - "false"
{{- end }}
{{- if .Values.config.oidc.issuer }}
          - --oidc.issuer
          - {{ .Values.config.oidc.issuer | quote }}
{{- end }}
{{- if .Values.config.oidc.secret }}
          - --oidc.secret
          - {{ .Values.config.oidc.secret | quote }}
{{- end }}
{{- if .Values.config.oidc.clientId }}
          - --oidc.clientid
          - {{ .Values.config.oidc.clientId | quote }}
{{- end }}
{{- if .Values.config.oidc.enforece }}
          - --oidc.enforce
{{- end }}
{{- range $scope := .Values.config.oidc.scopes }}
          - --oidc.scopes
          - {{ $scope | quote }}
{{- end }}

{{- if .Values.sentry.enabled}}
        - name: "SENTRY_DSN"
          value: {{ .Values.sentry.dsn | quote}}
{{- end }}
        ports:
          - containerPort:  {{ .Values.service.port }}
{{- if .Values.config.prometheus.enabled }}
          - containerPort: 9350
{{- end }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
        volumeMounts:
          - name: config-volume
            mountPath: /config/
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
{{- if .Values.nodeSelector }}
        nodeSelector:
{{ toYaml .Values.nodeSelector | indent 12 }}
{{- end }}
{{- if .Values.tolerations }}
        tolerations:
{{ toYaml .Values.tolerations | indent 12 }}
{{- end }}
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 10 }}
{{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: "{{ template "wallaby.fullname" . }}-config"
