{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "wallaby.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $uiServiceName := .Values.service.name -}}
{{- $uiServicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "wallaby.fullname" . }}
  labels:
    app: {{ template "wallaby.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ if  gt (len .Values.ingress.labels)  0 }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
  annotations:
    wallaby.autonubil.net/hidden: "true"
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
