{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "wallaby.fullname" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    app: {{ template "wallaby.fullname" . }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "wallaby.fullname" . }}
  labels:
    app: {{ template "wallaby.fullname" . }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  - apiGroups:
    - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
  - apiGroups:
    - ""
    resources:
    - pods/portforward
    verbs:
    - create
  - apiGroups:
    - extensions
    resources:
    - deployments
    verbs:
    - list
    - watch
    - get
  - apiGroups:
    - ""
    resources:
    - services
    verbs:
    - list
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "wallaby.fullname" . }}
  labels:
    app: {{ template "wallaby.fullname" . }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "wallaby.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "wallaby.fullname" . }}
  namespace: {{ .Release.Namespace}}
{{- end }}
