FROM gcr.io/distroless/base@sha256:a26dde6863dd8b0417d7060c990abe85c1d2481541568445e82b46de9452cf0c
LABEL maintainer="carsten.zeumer@autonubil.de"

COPY bin/default-backend-operator /bin/default-backend-operator
COPY configs/static /static

WORKDIR /bin

CMD ["/bin/default-backend-operator"]
